version: "3.9"  # optional since v1.27.0
services:
  spring-boot-web:
    build: .
    ports:
      - 8081:8080
    links:
      - postgres-db

  postgres-db:
    image: postgres:13
    environment:
        POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 5000:8080
    links:
      - postgres-db
      


